# Generated by Django 5.1.4 on 2024-12-05 18:49

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="produto",
            name="data_de_criacao",
            field=models.DateTimeField(
                verbose_name=datetime.datetime(2024, 12, 5, 15, 49, 41, 977710)
            ),
        ),
    ]
