# Generated by Django 4.2 on 2024-12-13 16:26

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="produto",
            name="data_de_criacao",
            field=models.DateTimeField(
                verbose_name=datetime.datetime(2024, 12, 13, 13, 26, 57, 385522)
            ),
        ),
    ]
